### ISSUE TITLE
Update to GraalVM 1.0-rc7

### ISSUE THREAD

**Issue by sdelamo** [micronaut-guides/micronaut-creating-first-graal-app#1]
https://www.graalvm.org/docs/release-notes/

**Comment by joschi** [comment]
Closed by 6687ce1088c1d9fc59a236c65781b63e2c3c547e

**Comment by sdelamo** [comment]
Thanks @joschi we have upgraded the guide to 1.0.0

**Comment by joschi** [comment]
@sdelamo Thanks!

Quick question: Are you generally open for external pull requests or rather not have them?
It seems like the existing ones were not seen or ignored when updating the guide.
