### ISSUE TITLE
oracle/graalvm-ce docker image does not exist anymore

### ISSUE THREAD

**Issue by debuglevel** [micronaut-guides/micronaut-creating-first-graal-app#23]
The `oracle/graalvm-ce` image does not seem to exist anymore.
https://github.com/micronaut-guides/micronaut-creating-first-graal-app/blob/b4e490b8e124dcb3ee8286c8f3c355fbb03fec38/complete/Dockerfile#L1

**Comment by ilopmar** [comment]
Thanks! That file is not necessary anymore because the Gradle/Maven plugins take care of it.

**Comment by rvramesh** [comment]
@ilopmar - When Dockerfile is removed, how can I reference this project in a docker-compose.yml without publishing to registry?

**Comment by ilopmar** [comment]
The Gradle plugin can generate the `Dockerfile` for you on-the-fly: https://github.com/micronaut-projects/micronaut-gradle-plugin#micronaut-application-plugin

If you need it or need to tweak something, generate it (`./gradlew dockerfile`), copy it to the root directory of the project and use it.

**Comment by rvramesh** [comment]
Thanks @ilopmar for a quick response.

I am in learning stage. I did check this option and it uses openjdk alpine. I wanted to get hold of the Native file. Native docker file passes all the referenced jars to native-image. Hence cannot keep it as static. Any other way which you would recommend?

I am trying to create a docker-compose.yml and add db and other images and reference the mirconaut app inside it. something like https://github.com/micronaut-projects/micronaut-examples/blob/master/petstore/docker-compose.yml

**Comment by rvramesh** [comment]
Currently I am having only one app. I created a .sh file and added the below

```
echo "Generating native docker file"
./gradlew dockerfileNative
echo
echo "running docker compose up"
docker-compose up
```

and in docker-compose.yml , I am referencing the dockerfile generated inside the builder folder like below

```
depends_on: 
      - db
    build:
      context: .
      dockerfile: build/docker/DockerfileNative
```

**Comment by ilopmar** [comment]
I'm sorry but I don't have enough docker-compose experience to help you with this.

**Comment by rvramesh** [comment]
@ilopmar Thank you.
